# Generated by Django 5.2 on 2025-04-11 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_date', models.DateField()),
                ('quantity_demanded', models.IntegerField()),
                ('demand_type', models.CharField(choices=[('actual', 'Actual'), ('forecast', 'Forecast')], default='actual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Demand Histories',
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='EOQParameters',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('annual_demand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_out_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('safety_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eoq_parameters', to='inventory.product')),
            ],
        ),
    ]
